//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace JwtWebApi.Link2DbProvider
{
	/// <summary>
	/// Database       : db_test_1
	/// Data Source    : tcp://localhost:7777
	/// Server Version : 13.1
	/// </summary>
	public partial class DbTest1DB : LinqToDB.Data.DataConnection
	{
		public ITable<AspNetRole>            AspNetRoles            { get { return this.GetTable<AspNetRole>(); } }
		public ITable<AspNetUser>            AspNetUsers            { get { return this.GetTable<AspNetUser>(); } }
		public ITable<AspNetUserRole>        AspNetUserRoles        { get { return this.GetTable<AspNetUserRole>(); } }
		public ITable<Attraction>            Attractions            { get { return this.GetTable<Attraction>(); } }
		public ITable<CateringType>          CateringTypes          { get { return this.GetTable<CateringType>(); } }
		public ITable<City>                  Cities                 { get { return this.GetTable<City>(); } }
		public ITable<CuisineType>           CuisineTypes           { get { return this.GetTable<CuisineType>(); } }
		public ITable<DenyType>              DenyTypes              { get { return this.GetTable<DenyType>(); } }
		public ITable<EquipmentType>         EquipmentTypes         { get { return this.GetTable<EquipmentType>(); } }
		public ITable<Hotel>                 Hotels                 { get { return this.GetTable<Hotel>(); } }
		public ITable<HotelEquipmentType>    HotelEquipmentTypes    { get { return this.GetTable<HotelEquipmentType>(); } }
		public ITable<HotelServiceType>      HotelServiceTypes      { get { return this.GetTable<HotelServiceType>(); } }
		public ITable<HousingType>           HousingTypes           { get { return this.GetTable<HousingType>(); } }
		public ITable<Restaurant>            Restaurants            { get { return this.GetTable<Restaurant>(); } }
		public ITable<RestaurantCoisineType> RestaurantCoisineTypes { get { return this.GetTable<RestaurantCoisineType>(); } }
		public ITable<RestaurantDenyType>    RestaurantDenyTypes    { get { return this.GetTable<RestaurantDenyType>(); } }
		public ITable<ServiceType>           ServiceTypes           { get { return this.GetTable<ServiceType>(); } }

		partial void InitMappingSchema()
		{
		}

		public DbTest1DB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbTest1DB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbTest1DB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="aspnet", Name="AspNetRoles")]
	public partial class AspNetRole
	{
		[PrimaryKey, Identity] public int    Id       { get; set; } // integer
		[Column,     Nullable] public string RoleName { get; set; } // character varying(40)
	}

	[Table(Schema="aspnet", Name="AspNetUsers")]
	public partial class AspNetUser
	{
		[PrimaryKey, NotNull    ] public string Id             { get; set; } // character varying(128)
		[Column,     NotNull    ] public string UserName       { get; set; } // character varying(255)
		[Column,     NotNull    ] public string Email          { get; set; } // character varying(255)
		[Column,        Nullable] public string PasswordHash   { get; set; } // character varying(255)
		[Column,        Nullable] public bool?  EmailConfirmed { get; set; } // boolean
		[Column,        Nullable] public string SecurityStamp  { get; set; } // character varying(255)
	}

	[Table(Schema="aspnet", Name="AspNetUserRoles")]
	public partial class AspNetUserRole
	{
		[Column, Nullable] public string AspNetUserId { get; set; } // character varying
		[Column, Nullable] public int?   RoleId       { get; set; } // integer
	}

	[Table(Schema="places", Name="Attractions")]
	public partial class Attraction : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int            Id          { get; set; } // integer
		[Column,     NotNull ] public string         Name        { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Preview     { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Description { get; set; } // character varying(255)
		[Column,     NotNull ] public int            CityId      { get; set; } // integer
		[Column,     NotNull ] public DateTimeOffset BuildDate   { get; set; } // timestamp (6) with time zone
		[Column,     NotNull ] public string         Address     { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Latitude    { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Longitude   { get; set; } // character varying(255)
		[Column,     NotNull ] public int            Duration    { get; set; } // integer
	}

	[Table(Schema="places", Name="CateringTypes")]
	public partial class CateringType : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}

	[Table(Schema="places", Name="Cities")]
	public partial class City : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}

	[Table(Schema="places", Name="CuisineTypes")]
	public partial class CuisineType : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}

	[Table(Schema="places", Name="DenyTypes")]
	public partial class DenyType : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}

	[Table(Schema="places", Name="EquipmentTypes")]
	public partial class EquipmentType : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}

	[Table(Schema="places", Name="Hotels")]
	public partial class Hotel : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int            Id            { get; set; } // integer
		[Column,     NotNull ] public string         Name          { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Preview       { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Description   { get; set; } // character varying(255)
		[Column,     NotNull ] public int            CityId        { get; set; } // integer
		[Column,     NotNull ] public DateTimeOffset BuildDate     { get; set; } // timestamp (6) with time zone
		[Column,     NotNull ] public string         Address       { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Latitude      { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Longitude     { get; set; } // character varying(255)
		[Column,     NotNull ] public int            HousingTypeId { get; set; } // integer
		[Column,     NotNull ] public int            ClassType     { get; set; } // integer
	}

	[Table(Schema="places", Name="HotelEquipmentTypes")]
	public partial class HotelEquipmentType : JwtWebApi.DataProviders.Common.DataObjects.IEntity
	{
		[PrimaryKey, Identity] public int  Id              { get; set; } // integer
		[Column,     Nullable] public int? HoletId         { get; set; } // integer
		[Column,     Nullable] public int? EquipmentTypeId { get; set; } // integer
	}

	[Table(Schema="places", Name="HotelServiceTypes")]
	public partial class HotelServiceType : JwtWebApi.DataProviders.Common.DataObjects.IEntity
	{
		[PrimaryKey, Identity] public int  Id            { get; set; } // integer
		[Column,     Nullable] public int? HoletId       { get; set; } // integer
		[Column,     Nullable] public int? ServiceTypeId { get; set; } // integer
	}

	[Table(Schema="places", Name="HousingTypes")]
	public partial class HousingType : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}

	[Table(Schema="places", Name="Restaurants")]
	public partial class Restaurant : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int            Id             { get; set; } // integer
		[Column,     NotNull ] public string         Name           { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Preview        { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Description    { get; set; } // character varying(255)
		[Column,     NotNull ] public int            CityId         { get; set; } // integer
		[Column,     NotNull ] public DateTimeOffset BuildDate      { get; set; } // timestamp (6) with time zone
		[Column,     NotNull ] public string         Address        { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Latitude       { get; set; } // character varying(255)
		[Column,     NotNull ] public string         Longitude      { get; set; } // character varying(255)
		[Column,     NotNull ] public int            CateringTypeId { get; set; } // integer
	}

	[Table(Schema="places", Name="RestaurantCoisineTypes")]
	public partial class RestaurantCoisineType : JwtWebApi.DataProviders.Common.DataObjects.IEntity
	{
		[PrimaryKey, Identity] public int  Id            { get; set; } // integer
		[Column,     Nullable] public int? RestaurantId  { get; set; } // integer
		[Column,     Nullable] public int? CuisineTypeId { get; set; } // integer
	}

	[Table(Schema="places", Name="RestaurantDenyTypes")]
	public partial class RestaurantDenyType : JwtWebApi.DataProviders.Common.DataObjects.IEntity
	{
		[PrimaryKey, Identity] public int  Id           { get; set; } // integer
		[Column,     Nullable] public int? RestaurantId { get; set; } // integer
		[Column,     Nullable] public int? DenyTypeId   { get; set; } // integer
	}

	[Table(Schema="places", Name="ServiceTypes")]
	public partial class ServiceType : JwtWebApi.DataProviders.Common.DataObjects.IEntity,JwtWebApi.DataProviders.Common.DataObjects.INamed
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column,     Nullable] public string Name { get; set; } // character varying(255)
	}
}

#pragma warning restore 1591
