//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace JwtWebApi.Link2DbProvider
{
	/// <summary>
	/// Database       : db_test_1
	/// Data Source    : tcp://localhost:7777
	/// Server Version : 13.1
	/// </summary>
	public partial class DbTest1DB : LinqToDB.Data.DataConnection
	{
		public ITable<AspNetUser>          AspNetUsers           { get { return this.GetTable<AspNetUser>(); } }
		public ITable<MyMigrationsHistory> MyMigrationsHistories { get { return this.GetTable<MyMigrationsHistory>(); } }
		/// <summary>
		/// Идентификатор
		/// </summary>
		public ITable<Object>              Objects               { get { return this.GetTable<Object>(); } }

		partial void InitMappingSchema()
		{
		}

		public DbTest1DB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbTest1DB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DbTest1DB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="aspnet", Name="AspNetUsers")]
	public partial class AspNetUser
	{
		[Column,     NotNull    ] public string UserId         { get; set; } // character varying(128)
		[Column,     NotNull    ] public string UserName       { get; set; } // character varying(255)
		[Column,     NotNull    ] public string Email          { get; set; } // character varying(255)
		[Column,        Nullable] public string PasswordHash   { get; set; } // character varying(255)
		[Column,        Nullable] public bool?  EmailConfirmed { get; set; } // boolean
		[Column,        Nullable] public string SecurityStamp  { get; set; } // character varying(255)
		[PrimaryKey, Identity   ] public int    Id             { get; set; } // integer
	}

	[Table(Schema="content", Name="__MyMigrationsHistory")]
	public partial class MyMigrationsHistory
	{
		[PrimaryKey, NotNull] public string MigrationId    { get; set; } // character varying(150)
		[Column,     NotNull] public string ProductVersion { get; set; } // character varying(32)
	}

	/// <summary>
	/// Идентификатор
	/// </summary>
	[Table(Schema="content", Name="Objects")]
	public partial class Object
	{
		/// <summary>
		/// Идентификатор
		/// </summary>
		[PrimaryKey, Identity] public int Id { get; set; } // integer
	}
}

#pragma warning restore 1591
