version: "3.9"
services:
  webapp:
    image: cheekibreeki228/test_repos:dev
    ports:
      - 22111:22111
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:22111
    secrets:
      - TravelDbConnectionString
      - JWTKey
      - GoogleSecret
    networks:
      - backend
networks:
  backend:
    external:
      name: dev
secrets:
   TravelDbConnectionString:
      file: ./TravelDbConnectionString
   JWTKey:
      file: ./JWTKey
   GoogleSecret:
      file: ./GoogleSecret
      