on:
  push:
    branches: 
     - develop
jobs:
  build_dev:

    name: Deploy Docker Image - DEV
    runs-on: [self-hosted, dev]
    
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
   
      - name: Rmi Images
        run: docker rmi cheekibreeki228/test_repos:dev --force
        
      - name: Build Images
        run: cd src/; docker build -t cheekibreeki228/test_repos:dev .
        
      - name: Deploy Image
        run:  cat /usr/app/dev/dockerhub_password | docker login --username cheekibreeki228 --password-stdin; docker push cheekibreeki228/test_repos:dev
  
      - name: Stop Service
        run: cd src/;docker-compose down --rmi all
        
      - name: Start Service
        run: cd src/;docker-compose up -d

