---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches-ignore: []

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Deploy Docker Image - DEV
    # Set the agent to run on
    runs-on: [self-hosted, linux, dev]
    # Prevent duplicate run from happening when a forked push is committed
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      ########################
      # Get the current date #
      ########################
      - name: Get current date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> ${GITHUB_ENV}

      ###################################
      # Build image locally #
      ###################################
      - name: Build Docker image
        run: docker rmi cheekibreeki228/test_repos:dev --force
        
      - name: Push Docker Image
        run: docker push cheekibreeki228/test_repos:dev
      ##############
      # Print info #
      ##############
      - name: Get Docker info
        run: docker images    
