on:
  push:
    branches-ignore: [master]
  pull_request:
    branches-ignore: []

jobs:
  build:

    name: Deploy Docker Image - DEV
    runs-on: self-hosted
  
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
 
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
   
      - name: Rmi Images
        run: docker build -t cheekibreeki228/test_repos:dev .

